version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: shopping-list-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopping_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
